### ISSUE TITLE
Modification for v3.0 interface board

### ISSUE THREAD

**Issue by n1kDon** [Victor-Mo/IRT-EMS-ESP#19]
Is there a guide how to modify the V3.0 interface board from BBQKees?

**Comment by Victor-Mo** [comment]
@n1kDon I have not look at the new interface board. The modified EMS boards do not always work. But the circuit suggested in #14 seems to work reliable you may want to have a look at that.

**Comment by n1kDon** [comment]
Thx!

**Comment by harrymayr** [comment]
@n1kDon The 100k you need to remove (R5 on the old gateway)  is R22 and the additional 1M5 resistor, need to be soldered between pin 2 & 8 of U2, or between the points marked in the attached grafik.

Best regards,

Harry
![V3-Modifikation](https://user-images.githubusercontent.com/104222469/204367084-a633ba5a-29de-475d-aa7d-0088cb015c80.PNG)

**Comment by vestaxbham** [comment]
Could somebody tell me what exact resistor is needed? 1M5 I understand. But there're different kinds of nominal load of each resistor, e.g. 0,25W.

Maybe somebody could past a link to the resistor that is needed? Or is it irrelevat what kind of nominal load a resistor has?

Thanks!

**Comment by mattes34** [comment]
Doesn’t matter. Use what you find. But i also can say that my case I  had to changed some more resistor values to get it working. I will search my measurements and results.

**Comment by vestaxbham** [comment]
Good to know, thanks!

It would be great if you could share some more of your experience. 👍

**Comment by n1kDon** [comment]
I soldered a 1,5M resistor between pin 2 & 8 of U2 but had no luck so far. No connection.

**Comment by vestaxbham** [comment]
> I soldered a 1,5M resistor between pin 2 & 8 of U2 but had no luck so far. No connection.

Did you also remove the R22?

**Comment by n1kDon** [comment]
Yes I did so. I damaged the pad of R22 after soldering the resistor to vcc. Therefore I soldered the resistor directly to pin 2 & 8

**Comment by harrymayr** [comment]
@n1kDon then step by step:

- did you set tx-mode to 4 (thermostat is still connected), or 5 (gateway is the only device on your boiler)?
- did you make any short-cut when you removed R22?
- do you see any telegrams if you telnet and use 'log j'?
`yes, but only/many crc errors`: play around with different resistors between 1M and 2M or use a 1M potentiometer/trimmer with a 680k resistor in series until the crc-errors are gone
`no`: where and how did you connect the gateway, direct at the boiler (which contacts), or at the thermostat?

**Comment by n1kDon** [comment]
@harrymayr 
1. I tryed it with both modes, with the thermostat connected and after that only with the gateway connected
2. I dont think so but I will double check
3. no I dont see any crc errors only the message that it is not connected when I log j
4. I connected the gateway on pin 3 and 4 like the thermostat (which I temporary disconnected) on the uba 4001 boiler

I will try to change the resistor tomorrow

**Comment by vestaxbham** [comment]
> I soldered a 1,5M resistor between pin 2 & 8 of U2 but had no luck so far. No connection.

Could you please take a picture of your work and post it here?

Cross my fingers that you figure out why it isn’t working as espected. :)

**Comment by mattes34** [comment]
Hi. I checked my board and I also changed the R3 from 360Ohm to 1800Ohm. Here I uploaded a ltspice simulation which used next to the osiloscope to get it working. https://github.com/mattes34/WEMOS-IRT

**Comment by n1kDon** [comment]
Hi, I tested it with 2M resistor but had no luck either. Only no iRT bus signal error. Here ist a picture with a 1M and 470k resistor in series. I am no expert, perhaps I did some stupid mistake.  
![unnamed](https://user-images.githubusercontent.com/51006573/207263529-cdb7cd1c-b1a3-4967-b845-3d551f310f03.jpg)

**Comment by vestaxbham** [comment]
> Hi. I checked my board and I also changed the R3 from 360Ohm to 1800Ohm. Here I uploaded a ltspice simulation which used next to the osiloscope to get it working. https://github.com/mattes34/WEMOS-IRT

So, you removed the R22 and added the 1,5M resistor. Additionally you changed the R3 from 360Ohm to 1800Ohm.
Do I understand correctly?

Is this needed because of the V3 PCB? It is not documented, isn‘t it? Or do I missed something?

Thanks!

**Comment by mattes34** [comment]
I refer to the numbering of this schematic
https://github.com/Victor-Mo/IRT-ESP/blob/master/doc/schematics/IRT-V09_schema.png
- Remove of the 100k R5
- add 1M5 from LM393 minus to 5V
- Change of R3 from 360 to 1k8

This was needed in **my** enviroment. Using this circuit to read the IRT bus is, let's say, more like a workaround. See
https://github.com/Victor-Mo/IRT-ESP/issues/14

So in my enviroment I get it running by increasing to 1k8 to get a higher amplitude for the LM393.

**Comment by vestaxbham** [comment]
> Hi, I tested it with 2M resistor but had no luck either. Only no iRT bus signal error. Here ist a picture with a 1M and 470k resistor in series. I am no expert, perhaps I did some stupid mistake.
> ![unnamed](https://user-images.githubusercontent.com/51006573/207263529-cdb7cd1c-b1a3-4967-b845-3d551f310f03.jpg)

Thanks for the picture! Looks good in my opinion.
Did you already change the R3, as mattes34 mentioned before? Idk but may be this could do the trick?!
Otherwise it could be that you damaged the PCB at R22 pad… But I‘m not an expert, too…

**Comment by vestaxbham** [comment]
> I refer to the numbering of this schematic https://github.com/Victor-Mo/IRT-ESP/blob/master/doc/schematics/IRT-V09_schema.png
> 
> * Remove of the 100k R5
> * add 1M5 from LM393 minus to 5V
> * Change of R3 from 360 to 1k8
> 
> This was needed in **my** enviroment. Using this circuit to read the IRT bus is, let's say, more like a workaround. See #14
> 
> So in my enviroment I get it running by increasing to 1k8 to get a higher amplitude for the LM393.

Thanks for the details. For the V3 PCB it is R22, right? 
as soon my Gateway arrives, I‘ll give it a try. :)

**Comment by harrymayr** [comment]
> * Change of R3 from 360 to 1k8

Please have in mind, that R3 (360R) is on the v3 Gateway R5 (near to D6).

**Comment by n1kDon** [comment]
I managed to get it working as described above without changing R3, used another esp-mini, thx all!
