### ISSUE TITLE
Great projekt. Will save my investment :), if...

### ISSUE THREAD

**Issue by mrwee** [Victor-Mo/IRT-EMS-ESP#2]
Hi,

A while ago I bought an EMS-ESP expecting it to work with my boiler. Unfortunately I found that the boiler only supports iRT, so I put the gateway away. By chance, I stumbled upon your project, which looks promising!

I just wondered if it's possible for you to provide a compiled .bin for the D1 mini? I can't seem to get PlatformIO, VSC etc. to work, so instead of wasting my time on all those components, I'd rather play around with your SW and the boiler :)

**Comment by proddy** [comment]
I think you'll find the automated latest build under https://github.com/Victor-Mo/IRT-EMS-ESP/releases

**Comment by Victor-Mo** [comment]
@proddy Thanks for the quick answer !

@mrwee Make sure to make the hardware modification to the EMS-ESP (see the Readme [https://github.com/Victor-Mo/IRT-EMS-ESP/blob/master/README.md](url) and scroll down to hardware change) . It will not work without the modification.

**Comment by mrwee** [comment]
Just ordred a new (modified) board from @proddy. Will try your code out as soon as the board arrives :)

**Comment by mrwee** [comment]
Received the modified board and fitted it. Does not seem to work though :).
So far I've:
1) Fitted/connected the modified board with external USB power (ESP does not get power without), to the boiler
2) Configured Wi-Fi
3) Via Telnet: "set tx_mode 4 / restart"
4) Get "Error! Unable to read the EMS bus"
5) log j gives me a lot of "Starting scheduled MQTT publish, despite it's been configured + disabled" plus:
00:01:47.411) irt_rawTelegram: 01: FE
(00:01:47.431) irt_rawTelegram: 01: FE
(00:01:47.451) irt_rawTelegram: 01: FE
(00:01:47.471) irt_rawTelegram: 01: F0
(00:01:47.492) irt_rawTelegram: 01: FE
(00:01:47.511) irt_rawTelegram: 01: FE
(00:01:47.532) irt_rawTelegram: 01: FE
(00:01:47.551) irt_rawTelegram: 01: FC
(00:01:47.571) irt_rawTelegram: 01: F0
(00:01:47.591) irt_rawTelegram: 01: F8
(00:01:47.611) irt_rawTelegram: 01: FE
(00:01:47.631) irt_rawTelegram: 01: FE
(00:01:47.651) irt_rawTelegram: 01: FE
(00:01:47.671) irt_rawTelegram: 01: FE
(00:01:47.691) irt_rawTelegram: 01: FE
(00:01:47.711) irt_rawTelegram: 01: F0
(00:01:47.731) irt_rawTelegram: 01: F0
(00:01:47.751) irt_rawTelegram: 01: FC
(00:01:47.771) irt_rawTelegram: 01: F0
(00:01:47.791) irt_rawTelegram: 01: F8
(00:01:47.811) irt_rawTelegram: 01: F8
(00:01:47.831) irt_rawTelegram: 01: F0
(00:01:47.852) irt_rawTelegram: 01: F0
(00:01:47.872) irt_rawTelegram: 01: FE
(00:01:47.891) irt_rawTelegram: 01: FE
(00:01:47.911) irt_rawTelegram: 01: F0
(00:01:47.931) irt_rawTelegram: 01: FE

Any way I can troubleshoot further?

Link to issue@proddy: https://github.com/proddy/EMS-ESP/issues/170

**Comment by Victor-Mo** [comment]
@mrwee From the linked issue i can see that you have an UBA4001. They are more tricky to get working.

You cannot use the Jack plug on the front of the boiler. You must connect the board at the thermostat and it needs power through the USB port.

Today I received some additional hardware. I should have some time to test different setups, because we are urged to stay at home....

Just give me some time test some different setups. Hopefully I can then advise you better.

**Comment by mrwee** [comment]
Progress :)
After good advise from @proddy, I've now got the gateway connected (with v1.9.5ib43)
![image](https://user-images.githubusercontent.com/6720774/76999008-4b522500-6956-11ea-98a9-cc8a15859da0.png)

tx_mode is still 4.
Running "devices scan" reveals nothing

Starting "log j" still spams with "Starting scheduled MQTT publish", but sorting the output provides:
`(00:04:28.277) irt_rawTelegram: 01: 03
(00:04:28.397) irt_rawTelegram: 01: 00
(00:04:29.397) irt_rawTelegram: 3F: 01 01 FE 82 82 01 01 1B 1B EC EC 00 FF 83 83 01 01 1C 1C F1 F1 00 FF 93 93 01 01 1D 1D E5 E5 00 FF 90 90 52 52 25 25 A0 A0 A3 5C C9 C9 05 05 61 61 5E 5E 03 FC 96 96 01 01 21 21 10 10 75 8A
01:39 05:04 07:CC 11:FF 15:04 16:00 17:FF 73:52 78:07 | 81:45 82:00 83:00 84:5F 8A:AF 90:A3 93:00 96:75 97:00 A3:07 A4:37 A6:37 A8:35 AA:F9 AB:01 C9:03 E1:4A EB:01 EC:04 ED:A2 EE:94 EF:35   0y
Publishing boiler data via MQTT
(00:04:29.517) irt_rawTelegram: 01: 02
(00:04:29.637) irt_rawTelegram: 01: 03
(00:04:29.737) irt_rawTelegram: 01: 00
(00:04:30.596) irt_rawTelegram: 31: 01 01 FE 97 97 01 01 1B 1B F9 F9 00 FF 84 84 01 01 1C 1C F6 F6 5F A0 8A 8A 01 01 1D 1D FC FC AF 50 73 73 52 52 25 25 43 43 78 78 06 06 00 00 74 74
01:39 05:04 07:CC 11:FF 15:04 16:00 17:FF 73:52 78:06 | 81:45 82:00 83:00 84:5F 8A:AF 90:A3 93:00 96:75 97:00 A3:07 A4:37 A6:37 A8:35 AA:F9 AB:01 C9:03 E1:4A EB:01 EC:04 ED:A2 EE:94 EF:35   0y
(00:04:30.696) irt_rawTelegram: 01: 02
(00:04:30.816) irt_rawTelegram: 01: 03
(00:04:30.936) irt_rawTelegram: 01: 00
(00:04:31.636) irt_rawTelegram: 25: 01 01 FE 81 81 01 01 1B 1B EF EF 45 BA 73 73 52 52 25 25 43 43 78 78 05 05 04 04 62 62 05 05 04 04 25 25 99 99
01:39 05:04 07:CC 11:FF 15:04 16:00 17:FF 73:52 78:05 | 81:45 82:00 83:00 84:5F 8A:AF 90:A3 93:00 96:75 97:00 A3:07 A4:37 A6:37 A8:35 AA:F9 AB:01 C9:03 E1:4A EB:01 EC:04 ED:A2 EE:94 EF:35   0y
(00:04:31.756) irt_rawTelegram: 01: 02
(00:04:31.876) irt_rawTelegram: 01: 03
(00:04:31.976) irt_rawTelegram: 01: 00
(00:04:32.855) irt_rawTelegram: 33: 01 01 FE 73 73 52 52 25 25 43 43 78 78 01 01 FF FF AD AD 01 01 39 39 04 04 63 63 73 73 52 52 25 25 43 43 78 78 07 07 FF FF A1 A1 07 07 CC CC 21 21 02 02
01:39 05:04 07:CC 11:FF 15:04 16:00 17:FF 73:52 78:07 | 81:45 82:00 83:00 84:5F 8A:AF 90:A3 93:00 96:75 97:00 A3:07 A4:37 A6:37 A8:35 AA:F9 AB:01 C9:03 E1:4A EB:01 EC:04 ED:A2 EE:94 EF:35   0y
(00:04:32.976) irt_rawTelegram: 01: 02
(00:04:33.075) irt_rawTelegram: 01: 03
(00:04:33.195) irt_rawTelegram: 01: 00
(00:04:34.195) irt_rawTelegram: 3F: 01 01 FE F0 F0 1F 1F FE FE 1D 1D 05 FA F0 F0 1F 1F FF FF 19 19 62 9D A4 A4 39 39 04 04 C6 C6 37 C8 A6 A6 52 52 25 25 96 96 38 C7 A8 A8 07 07 FF FF 71 71 35 CA A3 A3 CC CC 21 21 A6 A6 07 F8
01:39 05:04 07:CC 11:FF 15:04 16:00 17:FF 73:52 78:07 | 81:45 82:00 83:00 84:5F 8A:AF 90:A3 93:00 96:75 97:00 A3:07 A4:37 A6:38 A8:35 AA:F9 AB:01 C9:03 E1:4A EB:01 EC:04 ED:A2 EE:05 EF:62   0y
Publishing boiler data via MQTT
(00:04:34.315) irt_rawTelegram: 01: 02
(00:04:34.436) irt_rawTelegram: 01: 03
(00:04:34.534) irt_rawTelegram: 01: 00
(00:04:35.554) irt_rawTelegram: 3F: 01 01 FE F0 F0 01 01 1B 1B 9E 9E 01 FE F0 F0 01 01 1E 1E 8A 8A 94 6B F0 F0 01 01 1F 1F 8E 8E 35 CA AA AA 52 52 25 25 9A 9A F9 06 F0 F0 05 05 5B 5B 8F 8F 01 FE F0 F0 05 05 5C 5C 93 93 20 DF
01:39 05:04 07:CC 11:FF 15:04 16:00 17:FF 73:52 78:07 | 81:45 82:00 83:00 84:5F 8A:AF 90:A3 93:00 96:75 97:00 A3:07 A4:37 A6:38 A8:35 AA:F9 AB:01 C9:03 E1:4A EB:01 EC:20 ED:A2 EE:94 EF:35   0y
(00:04:35.654) irt_rawTelegram: 01: 02
(00:04:35.774) irt_rawTelegram: 01: 03
(00:04:35.894) irt_rawTelegram: 01: 00
(00:04:36.894) irt_rawTelegram: 3F: 01 01 FE F0 F0 01 01 1B 1B 9E 9E 01 FE F0 F0 01 01 1C 1C 82 82 04 FB F0 F0 01 01 1D 1D 86 86 A2 5D AB AB 52 52 25 25 9B 9B 01 FE F0 F0 05 05 61 61 67 67 36 C9 F0 F0 01 01 21 21 76 76 4A B5
01:39 05:04 07:CC 11:FF 15:04 16:00 17:FF 73:52 78:07 | 81:45 82:00 83:00 84:5F 8A:AF 90:A3 93:00 96:75 97:00 A3:07 A4:37 A6:38 A8:35 AA:F9 AB:01 C9:03 E1:4A EB:01 EC:04 ED:A2 EE:94 EF:35   0y
(00:04:37.013) irt_rawTelegram: 01: 02
(00:04:37.133) irt_rawTelegram: 01: 03
(00:04:37.233) irt_rawTelegram: 01: 00
`

**Comment by Victor-Mo** [comment]
Good news ! 

Could you share what you changed ?

The 'Starting scheduled MQTT publish..' is a bug and i need to fix it. But you can work around it by issuing the following command 'set publish_time 120'

I also noticed that the web gui is not showing the current temperature. I will investigate. The MQTT should work, that is what I am using. The 'info' command should show the information.

**Comment by mrwee** [comment]
Sure.
I connected the gateway via the terminal block on the boiler (PINS 3+4), and not the 3.5mm jack. ESP8266 gets separate USB power from an 230V adapter.

Nice with the MQTT 'fix' :)

MQTT data seen with MQTT Explorer:
{"wWSelTemp":0,"wWDesinfectionTemp":0,"selFlowTemp":0,"selBurnPow":0,"curBurnPow":0,"pumpMod":0,"wWCircPump":0,"outdoorTemp":0,"wWCurTmp":51,"wWCurFlow":0,"curFlowTemp":60,"retTemp":54,"switchTemp":0,"sysPress":0,"boilTemp":0,"wwStorageTemp1":0,"wwStorageTemp2":0,"exhaustTemp":0,"wWActivated":"off","wWOnetime":"off","wWCirc":"off","burnGas":"on","flameCurr":0,"heatPmp":"on","fanWork":"on","ignWork":"off","heating_temp":0,"pump_mod_max":0,"pump_mod_min":0,"wWHeat":"off","wWStarts":0,"wWWorkM":0,"UBAuptime":0,"burnStarts":0,"burnWorkMin":0,"heatWorkMin":0,"ServiceCode":"-H","ServiceCodeNumber":83}

But very nice that it's on it's way!

**Comment by mrwee** [comment]
Have now re-flashed the ESP to version 1.9.5ib44. Now the Dashboard is populated with more info :)

![2020-04-16_11-39-19](https://user-images.githubusercontent.com/6720774/79441155-301b1980-7fd7-11ea-804e-99cf26907fa2.png)

**Comment by Victor-Mo** [comment]
I have cleaned-up de webgui to only show valid values, basically only boiler values. The MQTT publish time is also working. So closing this issue.
