### ISSUE TITLE
OTA does not work from 1.9.5ib43 to 1.9.5ib44

### ISSUE THREAD

**Issue by mrwee** [Victor-Mo/IRT-EMS-ESP#3]
OTA updating from pre-compiled 1.9.5ib43 to pre-compiled 1.9.5ib44 via the GUI, does not work. The upload goes fine, but the version stays the same.

**Comment by Victor-Mo** [comment]
Thanks for reporting this. I will look into this.

**Comment by Victor-Mo** [comment]
I have fixed upgrading via the webGUI in version 1.9.7. But this will only work for future updates. Use espota.py to upgrade.

Closing this issue.
